import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from './Components/Navbar'
import AllProduct from './Components/AllProduct'
import Footer from './Components/Footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main >
          <div className='lg:px-48 px-5'>
         <Navbar/>
         <AllProduct/>
         </div>
        <Footer/>
        </main>
    </>
  )
}
